from transformers import IntervalStrategy

MODEL_CONFIG_V_POC = {
    'version': '_POC',
    'concat_with_wikiann': False,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 4,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_1 = {
    'version': '0.0.1',
    'concat_with_wikiann': True,
    'filter_numeric_wikiann_rows': False,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 8,
    'per_device_eval_batch_size': 8,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_2 = {
    'version': '0.0.2',
    'concat_with_wikiann': True,
    'filter_numeric_wikiann_rows': True,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 8,
    'per_device_eval_batch_size': 8,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_3 = {
    'version': '0.0.3',
    'concat_with_wikiann': True,
    'filter_numeric_wikiann_rows': True,
    'early_stopping_patience': 10,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 4,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_4 = {
    'version': '0.0.4',
    'concat_with_wikiann': True,
    'filter_numeric_wikiann_rows': True,
    'early_stopping_patience': 3,
    'hyperparameter_tuning':  True,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 4,
    'learning_rate': 0.000024981604754,
    'weight_decay': 0.285214291922975,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_5 = {
    'version': '0.0.5',
    'attention_probs_dropout_prob': 0.25,
    'hidden_dropout_prob': 0.2,    
    'classifier_dropout_value': 0.25,
    'concat_with_wikiann': True,
    'filter_numeric_wikiann_rows': True,
    'early_stopping_patience': 3,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 4,
    'learning_rate': 0.000024981604754,
    'weight_decay': 0.285214291922975,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}

MODEL_CONFIG_V0_0_6 = {
    'version': '0.0.6',
    'attention_probs_dropout_prob': 0.25,
    'hidden_dropout_prob': 0.2,    
    'classifier_dropout_value': 0.25,
    'early_stopping_patience': 3,
    'hyperparameter_tuning':  False,
    'evaluation_strategy': IntervalStrategy.EPOCH,
    'per_device_train_batch_size': 4,
    'per_device_eval_batch_size': 4,
    'learning_rate': 0.000024981604754,
    'weight_decay': 0.285214291922975,
    'num_train_epochs': 15,
    'logging_strategy': IntervalStrategy.EPOCH,
    'save_strategy': IntervalStrategy.EPOCH,
    'save_total_limit': 2,
    'eval_steps': 500,
    'load_best_model_at_end': True,
    'metric_for_best_model': 'f1',
}
